# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20170908_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='thread',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket'),
        ),
    ]
