# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20170908_1833'),
        ('vote', '0003_auto_20170911_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollsubject',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='subject',
        ),
        migrations.AddField(
            model_name='vote',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='PollSubject',
        ),
    ]
